### ISSUE TITLE
Can't install successfully!

### ISSUE THREAD

**Issue by benben-miao** [lch14forever/microbiomeViz#18]
1: All                          
2: CRAN packages only           
3: None                         
4: glue  (1.4.1 -> 1.4.2) [CRAN]
5: vctrs (0.3.2 -> 0.3.3) [CRAN]

Error : (由警告转换成)无法重新编码'visualizer.R'行155
ERROR: unable to collate and parse R files for package 'microbiomeViz'

**Comment by lch14forever** [comment]
The same with #17 .

**Comment by Morph0124** [comment]
Met the same error : 
Warning: 无法重新编码'visualizer.R'行155
Error in parse(outFile) : 
  E:/download/microbiomeViz-master/R/visualizer.R:155:44: 意外的'<'
154:         theme_classic() +
155:         facet_grid(group~., scale='free_y',<
                                                ^

**Comment by lch14forever** [comment]
Fixed in e22d7b1. Please try again.

**Comment by Morph0124** [comment]
Dear Chenhao Li,
       It is very appreciatable and helpful of your work and reply. Thanks a lot.

Yours,
Qiao
发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: Chenhao Li<mailto:notifications@github.com>
发送时间: 2020年9月3日 19:45
收件人: lch14forever/microbiomeViz<mailto:microbiomeViz@noreply.github.com>
抄送: Morph0124<mailto:qiaoliang0124@outlook.com>; Comment<mailto:comment@noreply.github.com>
主题: Re: [lch14forever/microbiomeViz] Can't install successfully! (#18)


Fixed in e22d7b1<https://github.com/lch14forever/microbiomeViz/commit/e22d7b19835f9b0b3d0785931bbd63b898f6299c>. Please try again.

―
